import * as functions from './modules/functions.js'

functions.isWebp()
functions.menu()
functions.burger()
functions.menuSpoiler()
functions.sliderSectionLast()
functions.sliderSectionPartners()
functions.sliderSectionTeam()
functions.blogTextSlice()
functions.tabs()
functions.modalSend()
functions.modalCall()
functions.modalThanks()
functions.maskPhoneNumber()
functions.validateModalSend()
functions.validateModalCall()
functions.validateServiceDetails()
functions.validateContacts()
